### ISSUE TITLE
@Config defaultValue does not work with booleans

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#550]
When using @Config annotation to load from config, the default value it loads (in the event it needs to) returns a string, not a boolean value. Boolean cannot properly load in this case.

Low priority, easy to fix with loaded configs, but still a thing to note.

```
class:
  assassin:
    receiveKnockback: 'true'
    dealKnockback: 'false'
```

```
[18:06:41 ERROR]: [me.mykindos.betterpvp.core.listener.loader.ListenerLoader] Failed to load listener
java.lang.IllegalArgumentException: Can not set boolean field me.mykindos.betterpvp.champions.champions.roles.listeners.AssassinListener.assassinDealKnockback to java.lang.String
        at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[?:?]
        at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[?:?]
        at jdk.internal.reflect.UnsafeBooleanFieldAccessorImpl.set(UnsafeBooleanFieldAccessorImpl.java:86) ~[?:?]
        at java.lang.reflect.Field.set(Field.java:799) ~[?:?]
        at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:51) ~[core.jar:?]
        at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146) ~[core.jar:?]
        at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:101) ~[core.jar:?]
        at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:72) ~[core.jar:?]
        at com.google.inject.internal.InjectorImpl.injectMembers(InjectorImpl.java:1062) ~[core.jar:?]
        at me.mykindos.betterpvp.core.listener.loader.ListenerLoader.load(ListenerLoader.java:27) ~[core.jar:?]
        at me.mykindos.betterpvp.core.listener.loader.ListenerLoader.load(ListenerLoader.java:40) ~[core.jar:?]
        at me.mykindos.betterpvp.champions.listeners.ChampionsListenerLoader.registerListeners(ChampionsListenerLoader.java:29) ~[champions.jar:?]
        at me.mykindos.betterpvp.champions.Champions.onEnable(Champions.java:69) ~[champions.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.4.jar:git-Paper-381]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-381]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:637) ~[paper-1.20.4.jar:git-Paper-381]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:548) ~[paper-1.20.4.jar:git-Paper-381]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.20.4.jar:git-Paper-381]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[paper-1.20.4.jar:git-Paper-381]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-381]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Mykindos** [comment]
I'm not sure how this has happened for you, when the type is boolean it has always saved the default value properly for me in the past. Even if its stored as a string in quotes, it shouldn't break things due to it using Boolean.parseBoolean to process the field

![image](https://github.com/Mykindos/BetterPvP/assets/5389944/6f9d17e6-7bf1-47b5-b0b7-951bae179bc7)

I'll investigate this later, it may have broken from another change recently

**Comment by Mykindos** [comment]
I just deleted those configs from config.yml and made the server regenerate them and they were populated as expected

```yml
class:
  assassin:
    dealKnockback: false
    receiveKnockback: true
```

**Comment by StudentAlleg** [comment]
Strange, will test again. 
This is the only way they could have got there, maybe it was something todo with stopping the server mid-load or not having database running? 
Those are the only way this could happen, I did not manually write it in. If I can't replicate, will close.

**Comment by StudentAlleg** [comment]
Unable to reproduce, unknown what caused this in the first place. Cannot rule out user error.
