### ISSUE TITLE
/c clanplayers and /c playerclans raise errors

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#758]
[17:51:44 WARN]: [Clans] Plugin Clans v1.0 generated an exception while executing task 74072
java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "content" is null
        at net.kyori.adventure.text.Component.text(Component.java:804) ~[?:?]
        at me.mykindos.betterpvp.core.utilities.UtilMessage.message(UtilMessage.java:95) ~[core.jar:?]
        at me.mykindos.betterpvp.clans.clans.commands.subcommands.GetPlayersOfClanSubCommand.lambda$execute$0(GetPlayersOfClanSubCommand.java:67) ~[clans.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[?:git-Paper-451]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[?:git-Paper-451]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[17:52:03 INFO]: StudentAlleg issued server command: /c clanplayers bpp
[17:52:03 INFO]: [me.mykindos.betterpvp.core.logging.appenders.LegacyAppender] StudentAlleg executed command: /c clanplayers bpp
[17:52:03 WARN]: [Clans] Plugin Clans v1.0 generated an exception while executing task 107298
java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "content" is null
        at net.kyori.adventure.text.Component.text(Component.java:804) ~[?:?]
        at me.mykindos.betterpvp.core.utilities.UtilMessage.message(UtilMessage.java:95) ~[core.jar:?]
        at me.mykindos.betterpvp.clans.clans.commands.subcommands.GetPlayersOfClanSubCommand.lambda$execute$0(GetPlayersOfClanSubCommand.java:67) ~[clans.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[?:git-Paper-451]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[?:git-Paper-451]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by StudentAlleg** [comment]
Should be fixed by #757
