### ISSUE TITLE
runtime error while using an ability

### ISSUE THREAD

**Issue by Polisvh** [Mykindos/BetterPvP#94]
Whenever I use any ability, the errors appear:

```
[13:12:58 ERROR]: [me.mykindos.betterpvp.core.framework.updater.UpdateEventExecutor] Could not execute updater onUpdate in me.mykindos.betterpvp.core.gamer.listeners.GamerListener
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.GeneratedMethodAccessor63.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at me.mykindos.betterpvp.core.framework.updater.UpdateEventExecutor.executeMethod(UpdateEventExecutor.java:84) ~[core-1.0.jar:?]
        at me.mykindos.betterpvp.core.framework.updater.UpdateEventExecutor.lambda$callUpdater$0(UpdateEventExecutor.java:79) ~[core-1.0.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-71]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1480) ~[paper-1.20.1.jar:git-Paper-71]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-71]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NumberFormatException: For input string: "0,2"
        at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[?:?]
        at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
        at java.lang.Double.parseDouble(Double.java:651) ~[?:?]
        at me.mykindos.betterpvp.core.utilities.UtilTime.trim(UtilTime.java:28) ~[core-1.0.jar:?]
        at me.mykindos.betterpvp.core.utilities.UtilTime.convert(UtilTime.java:46) ~[core-1.0.jar:?]
        at me.mykindos.betterpvp.core.cooldowns.Cooldown.getRemaining(Cooldown.java:33) ~[core-1.0.jar:?]
        at me.mykindos.betterpvp.core.cooldowns.CooldownManager.lambda$use$3(CooldownManager.java:71) ~[core-1.0.jar:?]
        at me.mykindos.betterpvp.core.utilities.model.display.ActionBar.nextComponent(ActionBar.java:81) ~[core-1.0.jar:?]
        at me.mykindos.betterpvp.core.utilities.model.display.ActionBar.show(ActionBar.java:55) ~[core-1.0.jar:?]
        at me.mykindos.betterpvp.core.gamer.listeners.GamerListener.lambda$onUpdate$0(GamerListener.java:46) ~[core-1.0.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at me.mykindos.betterpvp.core.gamer.listeners.GamerListener.onUpdate(GamerListener.java:45) ~[core-1.0.jar:?]
      
        ```

**Comment by Mykindos** [comment]
There is likely more to this, but i'd recommend just redoing your config files.

You've put something in your config as 0,2 which is invalid, you probably meant 0.2

**Comment by Polisvh** [comment]
In core config? I haven't touched any config files except this one, which was just database stuff. Redoing config changes nothing in that case

**Comment by Polisvh** [comment]
Also there are more errors, it's just so long I cannot even paste it here, there are examples

```
[13:42:49 ERROR]: [me.mykindos.betterpvp.core.framework.updater.UpdateEventExecutor] Could not execute updater processCooldowns in me.mykindos.betterpvp.core.cooldowns.CooldownListener
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.GeneratedMethodAccessor84.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at me.mykindos.betterpvp.core.framework.updater.UpdateEventExecutor.executeMethod(UpdateEventExecutor.java:84) ~[core-1.0.jar:?]
        at me.mykindos.betterpvp.core.framework.updater.UpdateEventExecutor.lambda$callUpdater$0(UpdateEventExecutor.java:79) ~[core-1.0.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-71]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-71]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NumberFormatException: For input string: "0,2"
        at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[?:?]
        at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
        at java.lang.Double.parseDouble(Double.java:651) ~[?:?]
        at me.mykindos.betterpvp.core.utilities.UtilTime.trim(UtilTime.java:28) ~[core-1.0.jar:?]
        at me.mykindos.betterpvp.core.utilities.UtilTime.convert(UtilTime.java:46) ~[core-1.0.jar:?]
        at me.mykindos.betterpvp.core.cooldowns.Cooldown.getRemaining(Cooldown.java:33) ~[core-1.0.jar:?]
        at me.mykindos.betterpvp.core.cooldowns.CooldownManager.lambda$processCooldowns$5(CooldownManager.java:157) ~[core-1.0.jar:?]
        at java.util.concurrent.ConcurrentHashMap.removeEntryIf(ConcurrentHashMap.java:1640) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap$EntrySetView.removeIf(ConcurrentHashMap.java:4836) ~[?:?]
        at me.mykindos.betterpvp.core.cooldowns.CooldownManager.lambda$processCooldowns$6(CooldownManager.java:155) ~[core-1.0.jar:?]
        at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603) ~[?:?]
        at me.mykindos.betterpvp.core.cooldowns.CooldownManager.processCooldowns(CooldownManager.java:154) ~[core-1.0.jar:?]
        at me.mykindos.betterpvp.core.cooldowns.CooldownListener.processCooldowns(CooldownListener.java:27) ~[core-1.0.jar:?]
        ... 11 more
[13:42:49 ERROR]: [me.mykindos.betterpvp.core.framework.updater.UpdateEventExecutor] Could not execute updater onUpdate in me.mykindos.betterpvp.core.gamer.listeners.GamerListener
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.GeneratedMethodAccessor58.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at me.mykindos.betterpvp.core.framework.updater.UpdateEventExecutor.executeMethod(UpdateEventExecutor.java:84) ~[core-1.0.jar:?]
        at me.mykindos.betterpvp.core.framework.updater.UpdateEventExecutor.lambda$callUpdater$0(UpdateEventExecutor.java:79) ~[core-1.0.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-71]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1480) ~[paper-1.20.1.jar:git-Paper-71]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-71]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NumberFormatException: For input string: "5,7"
        at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[?:?]
        at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
        at java.lang.Double.parseDouble(Double.java:651) ~[?:?]
        at me.mykindos.betterpvp.core.utilities.UtilTime.trim(UtilTime.java:28) ~[core-1.0.jar:?]
        at me.mykindos.betterpvp.core.utilities.UtilTime.convert(UtilTime.java:46) ~[core-1.0.jar:?]
        at me.mykindos.betterpvp.core.cooldowns.Cooldown.getRemaining(Cooldown.java:33) ~[core-1.0.jar:?]
        at me.mykindos.betterpvp.core.cooldowns.CooldownManager.lambda$use$3(CooldownManager.java:71) ~[core-1.0.jar:?]
        at me.mykindos.betterpvp.core.utilities.model.display.ActionBar.nextComponent(ActionBar.java:81) ~[core-1.0.jar:?]
        at me.mykindos.betterpvp.core.utilities.model.display.ActionBar.show(ActionBar.java:55) ~[core-1.0.jar:?]
        at me.mykindos.betterpvp.core.gamer.listeners.GamerListener.lambda$onUpdate$0(GamerListener.java:46) ~[core-1.0.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at me.mykindos.betterpvp.core.gamer.listeners.GamerListener.onUpdate(GamerListener.java:45) ~[core-1.0.jar:?]
        ... 13 more
        ```

**Comment by Mykindos** [comment]
redo the core config

**Comment by Polisvh** [comment]
I have redone that, and nothing changed, then I have redone the whole  server  and still nothing changed

**Comment by Mykindos** [comment]
can you upload your entire latest.log from /logs

**Comment by Polisvh** [comment]
[latest.log](https://github.com/Mykindos/BetterPvP/files/12840621/latest.log)

**Comment by Mykindos** [comment]
This is due to how numbers are formatted in your country, ill have a fix submitted shortly
